#define AAN_KNOP_REGISTER PF1
#define UIT_KNOP_REGISTER PF2
#define X_KNOP_REGISTER PF1
#define Y_KNOP_REGISTER PF2
#define MIN_KNOP_REGISTER PF1
#define PLUS_KNOP_REGISTER PF1
#define START_KNOP_REGISTER PF1
#define NOODSTOP_KNOP_REGISTER PF2

#define AAN_KNOP_INGEDRUKT PINF & (1 << AAN_KNOP_REGISTER)

void init_knoppen(){
    DDRF &= ~(1 << AAN_KNOP_REGISTER);
    DDRF &= ~(1 << UIT_KNOP_REGISTER);
    DDRF &= ~(1 << X_KNOP_REGISTER);
    DDRF &= ~(1 << Y_KNOP_REGISTER);
    DDRF &= ~(1 << X_KNOP_REGISTER);
    DDRF &= ~(1 << Y_KNOP_REGISTER);
    DDRF &= ~(1 << MIN_KNOP_REGISTER);
    DDRF &= ~(1 << PLUS_KNOP_REGISTER);
    DDRF &= ~(1 << START_KNOP_REGISTER);
    DDRF &= ~(1 << NOODSTOP_KNOP_REGISTER);
}
